-- backend/schema.sql
-- Skema idempotent untuk autentikasi (profiles) dan data IoT (sensor_data)

-- 1) Tabel profil user
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  full_name text,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT timezone('utc', now());

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "User can view their own profile" ON public.profiles;
DROP POLICY IF EXISTS "User can update their own profile" ON public.profiles;
DROP POLICY IF EXISTS "User bisa update profil sendiri" ON public.profiles;

CREATE POLICY "profiles_select_own"
  ON public.profiles
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = id);

CREATE POLICY "profiles_update_own"
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = id)
  WITH CHECK ((SELECT auth.uid()) = id);

-- 2) Trigger auto-create profile saat user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (new.id, new.raw_user_meta_data->>'full_name')
  ON CONFLICT (id) DO UPDATE
    SET full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name);

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Backfill profil untuk user lama (aman dijalankan berulang)
INSERT INTO public.profiles (id, full_name)
SELECT u.id, u.raw_user_meta_data->>'full_name'
FROM auth.users u
LEFT JOIN public.profiles p ON p.id = u.id
WHERE p.id IS NULL;

-- 3) Tabel data sensor IoT
CREATE TABLE IF NOT EXISTS public.sensor_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suhu double precision NOT NULL,
  kelembaban double precision NOT NULL,
  soil double precision NOT NULL,
  tds double precision NOT NULL,
  ldr double precision NOT NULL,
  plant_score double precision,
  health_status text,
  device_id text NOT NULL DEFAULT 'esp1',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- Tambah kolom scoring jika tabel sudah ada sebelumnya
ALTER TABLE public.sensor_data ADD COLUMN IF NOT EXISTS plant_score double precision;
ALTER TABLE public.sensor_data ADD COLUMN IF NOT EXISTS health_status text;

CREATE INDEX IF NOT EXISTS sensor_data_created_at_idx ON public.sensor_data (created_at DESC);

ALTER TABLE public.sensor_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read sensor data" ON public.sensor_data;

CREATE POLICY "Authenticated users can read sensor data"
  ON public.sensor_data
  FOR SELECT
  TO authenticated
  USING (true);

-- 4) Tabel riwayat penyiraman (Krisna)
CREATE TABLE IF NOT EXISTS public.watering_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id text NOT NULL DEFAULT 'esp1',
  duration_seconds int NOT NULL DEFAULT 10,
  triggered_by text NOT NULL DEFAULT 'manual',
  soil_before double precision,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS watering_history_created_at_idx ON public.watering_history (created_at DESC);

ALTER TABLE public.watering_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read watering history"
  ON public.watering_history
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Service role can insert watering history"
  ON public.watering_history
  FOR INSERT
  TO authenticated
  WITH CHECK (true);
